### ISSUE TITLE
Question about beam search algorithm

### ISSUE THREAD

**Issue by DongChanS** [flashlight/flashlight#588]
### Question
I wonder about the beam search algorithm that implemented in flashlight v0.3.
Why the beam search algorithm in wav2letter (flashlight-consolidated) is not directly proportional to beam size?

#### Additional Context
I experimented beam search decoding in wav2letter with ConvLM (LexiconFreeSeq2SeqDecoder).

Experiment setting
- nthread_decoder (#gpus) = 1
- flashlight version = v0.3 (cuda 11.1)
- Graphic card = RTX 3090

ex) beam size = 1 : 4.7 seconds 
```bash
I0510 07:58:45.780704  3892 memoryefficient_offline_inference_cpu_consolidated.cpp:480] [Decoder] LexiconFreeSeq2Seq decoder with token-LM loaded in thread: 0

#...

I0510 07:58:50.381270  3892 memoryefficient_offline_inference_cpu_consolidated.cpp:542] last trial Completed!
```

ex) beam size = 5 : 12.3 seconds 
```bash
I0510 07:48:53.354856  3877 memoryefficient_offline_inference_cpu_consolidated.cpp:480] [Decoder] LexiconFreeSeq2Seq decoder with token-LM loaded in thread: 0

#...

I0510 07:49:05.692427  3877 memoryefficient_offline_inference_cpu_consolidated.cpp:542] last trial Completed!
```

ex) beam size = 50 : 22.9 seconds
```bash
I0510 07:57:31.725507  3885 memoryefficient_offline_inference_cpu_consolidated.cpp:480] [Decoder] LexiconFreeSeq2Seq decoder with token-LM loaded in thread: 0

#...

I0510 07:57:54.681197  3885 memoryefficient_offline_inference_cpu_consolidated.cpp:542] last trial Completed!
```

**Comment by tlikhomanenko** [comment]
We do some optimizations on the beam search: first we have token beam, where we try to continue seq only with top tokens; second we have beamthreashold which throw away hyps which are far away from the best one. Also at every step of beam search there could be different number of hyps (because of lexicon) and thus you will have different number of hyps to sort/process at every decoding step. This all makes decoder dependence on the beam size not just linear.
