### ISSUE TITLE
FlashLight fails to install on Colab

### ISSUE THREAD

**Issue by agemagician** [flashlight/flashlight#624]
### Bug Description
I am trying to install the flashlight library on Colab but it fails, because it can't detect intel mkl.
Even after using "colab_install_deps.sh".

#### Reproduction Steps
I have created the following Colab example to replicate the error:
https://colab.research.google.com/drive/1Gtb61upINW6eP9RLpjCpHEhjWwM82Fs8?usp=sharing

### Platform and Hardware
Google Colab using Linux and cpu.

**Comment by agemagician** [comment]
@jacobkahn @tlikhomanenko any idea ?

**Comment by tlikhomanenko** [comment]
I see that you build flashlight with vcpkg. Simply just clone flashlight and run cmake for flashlight as we are doing in the tutorials , for example https://github.com/flashlight/flashlight/blob/master/flashlight/app/asr/tutorial/notebooks/FinetuneCTC.ipynb. Otherwise 1) vcpkg build will be very slow for colab (cc @jacobkahn who I believe tested this) 2) try to set `export MKLROOT` var before.

**Comment by agemagician** [comment]
Thanks a lot @tlikhomanenko .
It did work like charm.
I think you should add this note on the main readme.

Thanks agian.
