### ISSUE TITLE
Flashlight on ARM

### ISSUE THREAD

**Issue by giannisp-verneek** [flashlight/flashlight#687]
### Question
Based on the build from source instructions, I see that flashlight depends on packages that are Intel specific, such as MKL, oneDNN and others. Other dependencies such as `Arrayfire` support `arm64` processors.

Are there any build instructions to build Flashlight on an `arm64` processor?

**Comment by tlikhomanenko** [comment]
cc @jacobkahn

**Comment by jacobkahn** [comment]
@giannisp-verneek — we're working on adding a framework-agnostic tensor framework (the Flashlight `Tensor` abstraction) in addition to removing the dependency on oneDNN, MKL, etc ane making that flexible, with the hope if being able to plug in specific ARM-based computation stacks and get things running!

As of this time, there unfortunately isn't a path forward, but we'll be looking for others to integrate stacks that they'd find useful into Flashlight — let us know if that's something you're interested in doing!

**Comment by giannisp-verneek** [comment]
Hello @jacobkahn, thank you for the reply. I do not think I have the capacity to undertake this project right now. Thank you for the information.

I closed the issue as I think it is resolved from my end. Feel free to reopen it if you think it is important for your roadmap.

**Comment by fquirin** [comment]
Any news about Flashlight on ARM @jacobkahn ? 🙂

**Comment by jacobkahn** [comment]
@fquirin — as of last week, Flashlight builds on ARM and has CI baselines for Linux and macOS on arm64 to force build support. At this point, tensor libs are the other barrier. ArrayFire on ARM via OpenCL should be possible, as should oneDNN with AMD GPU support. Supporting those intrinsics better remains a work on progress, nonetheless.

**Comment by Aswin-coder** [comment]
Can i able to build flashlight repo on ARM processor? @jacobkahn

**Comment by jacobkahn** [comment]
@Aswin-coder — Flashlight should build with ARM, but we're only in the early stages of adding an optimized ARM tensor backend. Stay tuned here.

**Comment by Aswin-coder** [comment]
> @Aswin-coder — Flashlight should build with ARM, but we're only in the early stages of adding an optimized ARM tensor backend. Stay tuned here.

Is it possible to build this repo without Intel mkl on ARM?

**Comment by jacobkahn** [comment]
@Aswin-coder — you can set `FL_USE_MKL=OFF` as a CMake option (as in `-DFL_USE_MKL=OFF`) at build time to not have the MKL dependency.

In general, building on ARM should be identical to building on other platforms. Things you won't have on ARM right now:
- a tensor backend besides oneDNN for doing computation. ArrayFire may run on ARM with the CPU backend (or possibly OpenCL), but I haven't tested this directly with Flashlight. We may need to make some modifications to the build, but the [`FL_ARRAYFIRE_USE_OPENCL`](https://github.com/flashlight/flashlight/blob/main/flashlight/fl/tensor/backend/af/CMakeLists.txt#L21) option _should_ set up everything properly.
- support for distributed training, since Gloo doesn't build on ARM last I checked.

As I mentioned above, this is very much a work in progress, and I'm hoping to start work on an ARM backend (with a very others) in the very near future that leverages the [ACL](https://github.com/ARM-software/ComputeLibrary) as an [`fl::Tensor`](https://github.com/flashlight/flashlight/tree/main/flashlight/fl/tensor#readme) backend, possibly in conjunction with the JIT. Look for a public-facing design document on that soon.
